spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Hey Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}ed50e4983bd6a40446f06d3bcd8b834bda57d9e8c0bb84220da83b412d6bd51def3328e050a0ba28d1d24ef12511972d"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
